Added custom_bug_codes and custom_non_bug_codes
microsoft/restler-fuzzer pull request #58
Opened 2020-11-17 00:46 UTC by rifiles

## Summary of the Pull Request
Added custom_bug_codes and custom_non_bug_codes to restler settings and HttpResponse has_bug_code logic.

## PR Checklist
* [x] Applies to work item: Closes #8
* [x] CLA signed.
* [ ] Tests added/passed.  
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different approach.

## Info on Pull Request

* If custom_bug_codes list is specified in settings file, any status codes specified in the list will trigger bugs if received from the service in test.
* If custom_non_bug_codes list is specified, all status codes that are _not_ specified in this list will be trigger bugs.
* custom_bug_codes and custom_non_bug_codes list must be mutually exclusive - if both are specified then an error is raised.
* The * and ? wildcards can be used when specifying status codes
* Added new settings to SettingsFile.md

## Validation Steps Performed

cd restler-fuzzer/restler
python -m pytest ./unit_tests

Ran quick-start script

Tested on unit test server with:
* No lists specified
  * Passed with no change
* Both lists specified
  * Error handled
* Non-string type specified in list
  * Error handled
* custom_bug_codes with various codes specified
  * Successfully logged bugs included in list and 500 bugs
* custom_non_bug_codes with various codes specified
  * Successfully logged any code not in the list
* custom_non_bug_codes with '500' in the list
  * Ignored 500 code
* Tested wildcard handling for * and ?

2020-11-17 04:53 UTC, marina-p commented
Please also add these to the settings json that contains all settings

2020-11-17 04:55 UTC, marina-p commented on docs/user-guide/SettingsFile.md
> +
Please provide an example that also shows the regex format (right now that is not documented, as far as I can tell)

2020-11-17 04:57 UTC, marina-p commented on restler/engine/transport_layer/response.py
> +                for code in Settings().custom_non_bug_codes:
suggest rephrasing 'All codes except the ones in that list should be flagged as bugs.  Hence, return False ...'

2020-11-17 04:57 UTC, marina-p requested changes
:clock1:

2020-11-18 06:21 UTC, marina-p commented
@rifiles I believe this one is not resolved yet

---
In reply to: [728684979](https://github.com/microsoft/restler-fuzzer/pull/58#issuecomment-728684979) [](ancestors = 728684979)

2020-11-18 06:35 UTC, rifiles commented
> @rifiles I believe this one is not resolved yet
> 
> In reply to: [728684979](https://github.com/microsoft/restler-fuzzer/pull/58#issuecomment-728684979) [](ancestors = 728684979)

You're right, missed that one.

2020-11-18 20:53 UTC, marina-p approved these changes
:shipit:

2020-11-18 21:47 UTC, merged